### PR TITLE
make BaseAddress optional

### PR DESCRIPTION
**Pull request by MaxDeg**
Usefull in environment where the BaseAddress is retreived dynamically (service discovery, local load balancing) and still keeping only one HttpClient

### CODE REVIEW

**Comment by bennor** [comment]
Seems okay to me. I assume all tests are still passing?

**Comment by MaxDeg** [comment]
Yes indeed

**Comment by onovotny** [comment]
@MaxDeg One last thing before we merge it - can you please add a unit test or two around this property?

**Comment by MaxDeg** [comment]
I think this pull request must be cancelled.
When trying to write some tests I faced an issue with HttpClient. The SendAsync version that refit use is not overridable. This methods perform check or HttpRequestMessage  to ensure the request uri is Absolute or that a BaseAddress is defined on HttpClient.

**Comment by onovotny** [comment]
Is there another approach that would meet your objectives?

**Comment by MaxDeg** [comment]
Well to be honest I don't see any except setting a fake BaseAddress to override.

**Comment by onovotny** [comment]
Closing for now

**Pull request closed without merging**
