### PR TITLE
Allow AutoGenerated classes to be internal.

### PR DESCRIPTION
**Pull request by ncruces**
Implements feature discussed in #167.

### CODE REVIEW

**Comment by bennor** [comment]
This looks good to me! :+1:

**Comment by onovotny** [comment]
Just one question. What if someone wants the interface to be internal but expose the data types?

**Comment by ncruces** [comment]
We have this:
```C#
internal interface IRemoteApi
{
    Task<User> GetUser(string id);
}
```

Refit generates this:
```C#
public partial class AutoGeneratedIIRemoteApi : IRemoteApi
{
    ... 
}
```

Which is typically used as:
```C#
var service = RestService.For<IRemoteApi>(url);
```

Since `IRemoteApi` is internal, what exactly is the point of the implementing class being public? Is it common to reference `AutoGeneratedIIRemoteApi` directly from another assemblies?

I may very well be missing some use case (the class is explicitly partial and open for extension, after all). But I'm failing to see the case where it makes sense for the interface to be internal and the class public, on the default configuration.

**Comment by onovotny** [comment]
Oh, I misunderstood. The AutoGenerated* class should def be internal then. I was thinking about the parameter types, but those wouldn't be generated :)

**Comment by ncruces** [comment]
Right, where this fails for me is that if the parameters/return types are internal (mine are) the class *can't* be made public.

But making those internal was my design choice. I have internal, mutable DTOs, which I implement public, readonly-view interfaces for outside consumption.

**Comment by onovotny** [comment]
Yup, totally get it :+1:

**Comment by ncruces** [comment]
Great! :+1: You can close #167.

**Pull request merged**
