### PR TITLE
Don't barf on readonly files if contents haven't changed

### PR DESCRIPTION
**Pull request by onovotny**
Fix for #94

### CODE REVIEW

**Comment by bennor** [comment]
This looks good to me now. 

Still a couple of minor format things (like the way R# indents chained method calls), but I think that can be cleaned up when merging. @paulcbetts: you happy with this?

**Comment by paulcbetts** [comment]
@bennor I'll merge this and fix up the rest of the jacked formatting soon

**Comment by paulcbetts** [comment]
Thanks @onovotny!

**Comment by bennor** [comment]
:+1:

**Pull request merged**
