### PR TITLE
Added a handful of tests for URL-encoded query string parameters

### PR DESCRIPTION
**Pull request by mteper**
I'm investigating a case where it seems Refit is not URL-encoding query string parameters. Haven't yet gotten to the bottom of it, but thought these unit tests (which pass) wouldn't hurt to have in the code base.

### CODE REVIEW

**Comment by onovotny** [comment]
@mteper any chance you can rebase this on master and I can merge?

**Comment by mteper** [comment]
@onovotny done.

**Comment by onovotny** [comment]
Not sure why this PR is showing >50 unrelated changes. @shiftkey, any idea how to clean this up?

**Comment by shiftkey** [comment]
@onovotny @mteper haven't been able to sync the PR on my end successfully, but here's how it looks locally:

```
$ git log  HEAD...origin/master --oneline
39c7129 Removed duplicate method
2a6b1eb Merge branch 'url-encoding-unit-tests' of https://github.com/mteper/refit into url-encoding-unit-tests
273f409 Added a handful of tests for URL-encoded query string parameters
5f7f9f7 Added a handful of tests for URL-encoded query string parameters
$ git diff --stat HEAD..origin/master
 Refit-Tests/RequestBuilder.cs | 13 -------------
 1 file changed, 13 deletions(-)
```

273f409c622b21809d4617cdfe2b98bf818e8f35 and  5f7f9f74c1f85f078d536ca02746d4aaf85dc888 look like overlapping commits, which might be confusing things (not that this is your fault). Can they be squashed together?

**Comment by onovotny** [comment]
closing this due to age. I also just fixed a bunch of Url Encoding issues in #421. Please check latest and see if there are still issues to resolve.

**Pull request closed without merging**
