### PR TITLE
implement MethodOverload

### PR DESCRIPTION
**Pull request by windischb**
I have changed the code in RequestBuilderImplementation.
RestMethodInfos are collected in a ConcurrentDictionary<string, List<RestMethodInfo>>.
This allows to collect also overloaded Methods.
When executing the RestMethod, the best matching Method will be picked.
Finding the correct Method is based on Reflection, to find the Method with matching parameter types.

### CODE REVIEW

**Comment by windischb** [comment]
Any updates on this?
Because i'm needing this functionality on another Project and i would prefer to use your "Main" Project instead of my Fork...

**Comment by onovotny** [comment]
Will probably be sometime this weekend as I've been very busy this week.

**Comment by elv1s42** [comment]
Hi!
Any updates so far?
This feature is very useful!

**Comment by onovotny** [comment]
There are currently conflicts that need to be resolved

**Pull request closed without merging**
