### PR TITLE
Uri template

### PR DESCRIPTION
**Pull request by darrelmiller**
This PR createsa pluggable URLTemplateHandler property on RefitSettings so that RFC 6570 URI Templates can be used with a replacement URLTemplateHandler.  I did not include that new handler in this PR so as to not introduce a dependency on Tavis.UriTemplates in refit.  
If this PR is accepted then I would release a new Nuget Package that implements a handler that looks like this https://gist.github.com/darrelmiller/deff3525791be6470520

### CODE REVIEW

**Comment by paulcbetts** [comment]
Can you give an example of what this would look like with RFC 6570 URIs? I feel like this PR basically means if you enable this, all of the documentation is completely wrong, it's basically a different library.

**Comment by darrelmiller** [comment]
The only breaking change that I am aware of is that URI Templates require query parameters to be specified, so you would need to do,

[Get("/users/list{?sort}")]

to be able to have sort as a query parameter.  The rest of the URI template capabilities are a superset of what your documentation covers.

It might be possible to get around the query string parameter issue.  My URITemplate library does have ways of generating the template based on parameters that are available.  Whether that is what people would want is a different matter.  This wasn't my idea in the first place ;-)

**Comment by jzeferino** [comment]
@paulcbetts This PR makes a lot of sense since it allows the developer to change the way the URL template are resolve. Using this PR along with Tavis.UriTemplate we could support the URI Template Spec RFC6570 level 4. Here are some examples of what can be achieved with this PR integrated with Tavis.UriTemplate: https://github.com/uri-templates/uritemplate-test/blob/master/spec-examples.json

Please take a look at scenarios implementing level 4, from line 59.

@darrelmiller I would like to help with this PR, if @paulcbetts make it possible.

**Comment by onovotny** [comment]
Closing due to age and changes since then.

**Comment by jzeferino** [comment]
@onovotny is the current version of refit supporting the URI Template Spec RFC6570 level 4?

**Comment by onovotny** [comment]
Refit has its own scheme, it's not specifically compliant with any RFC's.

**Comment by jzeferino** [comment]
Thank you.

**Pull request closed without merging**
