### PR TITLE
Use NetCore45 TFM instead of WinRT45

### PR DESCRIPTION
**Pull request by onovotny**
The WinRT45 TFM is obsolete and should not be used. NetCore45 is the correct replacement.

### CODE REVIEW

**Comment by bennor** [comment]
:+1:

**Comment by onovotny** [comment]
No code changes; it's the same binary just using the correct TFM in NuGet

**Comment by onovotny** [comment]
This now includes a fix to write the RefitStubs.g.cs file into the \obj dir. This is better as generated files should not be checked in anyway. This should also eliminate read-only issues as the file isn't checked in; it's created on-the-fly.

**Comment by onovotny** [comment]
Addresses #159

**Comment by mburbea** [comment]
:+1:

**Pull request merged**
