### PR TITLE
Add overload support by mangling method names

### LINKED ISSUE #82: Overloaded method support
As of now, refit doesn't handle method overload.
The methods dictionary can't be built because of DuplicateKeyException.

Would it be interesting to support WebApi's style method overload ?

``` C#
IEnumerable<X> Get();
X Get(int id);
```

### PR DESCRIPTION
**Pull request by nekresh**
Refit now support method overloading.
The methods dictionary is built using mangled method name instead of using the method name only.

I'm not quite sure about the Mangle method position (currently in RequestBuilder type).

Closes #82.

### CODE REVIEW

**Comment by ahmedalejo** [comment]
@nekresh What is the state of this merge?

**Comment by nikeee** [comment]
I think this PR looks fine.

**Comment by onovotny** [comment]
@nekresh can you please rebase this on master?

**Comment by onovotny** [comment]
closing this due to age. refit also now has overload support, thanks!

**Pull request closed without merging**
