### PR TITLE
Header fixes

### PR DESCRIPTION
**Pull request by bennor**
This PR contains the fixes for both of the outstanding header related bugs (#121 and #136).

* Adding of all headers is now deferred until the body parameter has been added to the request. This means `Content` is there and we can add headers to it.
* We now only try to add to the content headers collection if adding to the request headers collection failed.

Okay

### CODE REVIEW

**Comment by RTodorov** [comment]
Cool! Thanks a lot @bennor !

**Comment by adrianolc** [comment]
@bennor do you know when this fix will be released?

**Comment by bennor** [comment]
@adrianolc & @RTodorov: this is up on NuGet now (in v2.3.0).

**Comment by RTodorov** [comment]
Thanks a lot @bennor

**Pull request merged**
